const legacySeedTeams=[{id:'ansan',name:'안산시청',league:'2026 안산리그',players:[[27,'김민성','SS',''],[17,'이정훈','2B',''],[36,'박준영','CF',''],[10,'최현우','1B',''],[52,'정재훈','LF',''],[33,'김도현','RF',''],[7,'이서준','3B',''],[21,'한승민','C',''],[18,'오지환','DH',''],[99,'김태우','P','']]},{id:'twins',name:'Twins',league:'2026 안산리그',players:[[6,'이상균','SS',''],[8,'송창주','2B',''],[1,'김학률','CF',''],[2,'백종승','1B',''],[4,'최인태','LF',''],[5,'김진영','RF',''],[3,'이상수','3B',''],[9,'이종락','C',''],[7,'김동인','DH',''],[10,'김학률','P','']]},{id:'blue',name:'블루웨이브',league:'2026 주말리그',players:[[11,'박민수','P',''],[23,'김준호','C',''],[7,'이현우','SS',''],[31,'정태성','CF',''],[5,'최성민','1B',''],[18,'강현수','RF',''],[9,'박재윤','2B',''],[44,'윤지호','LF',''],[2,'한지훈','3B','']]}];

const seedTeams=DEMO_ROSTERS;
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=o=>JSON.parse(JSON.stringify(o));
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
let teams=read('ansan-teams-v4',clone(seedTeams)),leagues=read('ansan-leagues-v4',['첨부 팀 구성 · 테스트 리그']);
let game=read('ansan-match-v5',null),archive=read('ansan-archive-v5',[]),undoStack=[],draft=null,editId=teams[0]?.id;
// Add the requested eight-team dataset once; back up the previous DB first.
if(!read('ansan-eight-teams-v1',false)){
 const previous=clone(teams);const backedUp=persist('ansan-before-eight-teams',previous);
 if(backedUp){
  teams=teams.filter(t=>{const old=legacySeedTeams.find(q=>q.id===t.id);if(!old)return true;return t.name!==old.name||t.league!==old.league||t.players.some((p,i)=>!old.players[i]||JSON.stringify(p.slice(0,3))!==JSON.stringify(old.players[i].slice(0,3))||!!p[3])});
  for(const t of DEMO_ROSTERS)if(!teams.some(q=>q.id===t.id))teams.push(clone(t));
  leagues=['첨부 팀 구성 · 테스트 리그',...new Set(teams.map(t=>t.league).filter(l=>l!=='첨부 팀 구성 · 테스트 리그'))];
  if(persist('ansan-teams-v4',teams)&&persist('ansan-leagues-v4',leagues))persist('ansan-eight-teams-v1',true);
 }
 editId=teams.find(t=>t.id==='demo-eight-1')?.id||teams[0]?.id;
}
let channel;try{channel=new BroadcastChannel('ansan-game-v4')}catch{}
const team=id=>teams.find(t=>t.id===id), side=()=>game?.half==='초'?'a':'h',opponent=()=>side()==='a'?'h':'a',line=s=>game?.lineups[s]||[],current=()=>line(side())[game?.turns[side()]||0];
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function persist(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{toast('저장 공간이 부족합니다. 사진을 줄이거나 DB를 백업해 주세요.');$('saveState').textContent='저장 실패 · DB 백업 필요';return false}}
function saveDB(){persist('ansan-teams-v4',teams);persist('ansan-leagues-v4',leagues)}
function saveGame(){if(!game)return;const ok=persist('ansan-match-v5',game);channel?.postMessage({type:'match-v5',game});if(ok)$('saveState').textContent='저장됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});renderRecord()}
function act(label,fn){if(!game){toast('경기 준비에서 라인업을 먼저 확정하세요.');return}if(game.finished){toast('종료된 경기입니다. 새 경기를 준비하세요.');return}undoStack.push(clone(game));if(undoStack.length>80)undoStack.shift();fn();game.log.unshift({time:new Date().toLocaleTimeString('ko-KR'),label});game.log=game.log.slice(0,100);saveGame()}
function openPage(id){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===id));$('pageTitle').textContent={dashboard:'협회 운영 대시보드',record:'기록원 대시보드',setup:'경기 준비',teams:'팀 · 선수 관리',history:'경기 기록'}[id];if(id==='dashboard')renderDashboard();if(id==='setup'){selectors();renderDraft()}if(id==='teams')renderTeams();if(id==='history')renderHistory()}
function selectors(){const old=$('leagueSelect').value;$('leagueSelect').innerHTML=leagues.map(l=>`<option>${esc(l)}</option>`).join('');if(leagues.includes(old))$('leagueSelect').value=old;filterTeams()}
function filterTeams(){const ts=teams.filter(t=>t.league===$('leagueSelect').value),a=$('awaySelect').value,h=$('homeSelect').value;for(const id of ['awaySelect','homeSelect'])$(id).innerHTML=ts.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');$('awaySelect').value=ts.some(t=>t.id===a)?a:ts[0]?.id||'';$('homeSelect').value=ts.some(t=>t.id===h)&&h!==$('awaySelect').value?h:ts[1]?.id||''}
function loadDraft(){const a=team($('awaySelect').value),h=team($('homeSelect').value);if(!a||!h||a.id===h.id){toast('서로 다른 두 팀을 선택하세요.');return}draft={a:clone(a),h:clone(h),entries:{a:a.players.slice(0,9).map((_,i)=>i),h:h.players.slice(0,9).map((_,i)=>i)}};renderDraft()}
function photo(p,cls='avatar'){const image=playerPhoto(p);return `<div class="${cls} photo-frame">${image.src?`<img loading="lazy" src="${esc(image.src)}" alt="${image.sample?'야구선수 샘플 사진':esc(p?.[1])}">`:esc(p?.[0]||'—')}${image.sample?'<span class="sample-badge">샘플 사진</span>':''}</div>`}

function renderDraft(){if(!draft){$('entryPanels').innerHTML='<div class="card empty">리그와 두 팀을 선택한 뒤 명단을 불러오세요.</div>';return}$('entryPanels').innerHTML=['a','h'].map(s=>`<article class="card"><div class="card-head"><span class="tag ${s==='a'?'away':'home'}">${s==='a'?'AWAY':'HOME'}</span><h2>${esc(draft[s].name)}</h2><small>${draft.entries[s].length}명 선택</small></div><div class="entry-grid">${draft[s].players.map((p,i)=>`<button class="player-tile ${draft.entries[s].includes(i)?'selected':''}" data-action="entry" data-side="${s}" data-index="${i}">${photo(p)}<b>#${esc(p[0])} ${esc(p[1])}</b><small>${esc(p[2])} ${draft.entries[s].includes(i)?'✓':''}</small></button>`).join('')||'<p>팀·선수 관리에서 선수를 등록하세요.</p>'}</div><h3>오늘의 타순</h3>${draft.entries[s].map((i,n)=>`<div class="order-row"><b>${n+1}</b><span>#${esc(draft[s].players[i][0])} ${esc(draft[s].players[i][1])}</span><button data-action="move" data-side="${s}" data-index="${n}" data-value="-1" ${n===0?'disabled':''}>▲</button><button data-action="move" data-side="${s}" data-index="${n}" data-value="1" ${n===draft.entries[s].length-1?'disabled':''}>▼</button></div>`).join('')}<h3>선발 투수</h3><select id="pitch-${s}">${draft[s].players.map((p,i)=>`<option value="${i}" ${p[2]==='P'?'selected':''}>#${esc(p[0])} ${esc(p[1])}</option>`).join('')}</select></article>`).join('')}
function startGame(){if(!draft||!draft.entries.a.length||!draft.entries.h.length){toast('양 팀 출전 선수를 선택하세요.');return}if(game&&!game.finished&&!confirm('진행 중인 경기 대신 새 경기를 시작할까요? 기존 경기는 경기 기록에 보관됩니다.'))return;if(game&&!game.finished){archive.unshift({...clone(game),interrupted:true});persist('ansan-archive-v5',archive)}game={id:Date.now(),league:draft.a.league,teamNames:{a:draft.a.name,h:draft.h.name},lineups:{a:draft.entries.a.map(i=>clone(draft.a.players[i])),h:draft.entries.h.map(i=>clone(draft.h.players[i]))},rosters:{a:clone(draft.a.players),h:clone(draft.h.players)},pitchers:{a:+$('pitch-a').value,h:+$('pitch-h').value},turns:{a:0,h:0},scores:{a:Array(12).fill(null),h:Array(12).fill(null)},stats:{a:{H:0,E:0,B:0},h:{H:0,E:0,B:0}},inn:1,half:'초',b:0,s:0,o:0,bases:[0,0,0],speed:0,event:'경기 시작',blank:false,log:[],finished:false};game.scores.a[0]=0;undoStack=[];saveGame();openPage('record');toast('라인업을 저장했습니다. 기록을 시작하세요.')}
function runs(s,n){while(game.scores[s].length<game.inn)game.scores[s].push(null);game.scores[s][game.inn-1]=Math.max(0,(game.scores[s][game.inn-1]||0)+n)}
function next(){game.turns[side()]=(game.turns[side()]+1)%line(side()).length;game.b=game.s=0}
function switchSide(){game.half=game.half==='초'?'말':'초';if(game.half==='초')game.inn++;game.b=game.s=game.o=0;game.bases=[0,0,0];runs(side(),0);game.event='공수 교대'}
function outLogic(advance=true){game.o++;game.b=game.s=0;if(advance)next();if(game.o>=3)switchSide()}
function walkLogic(label){const s=side();game.event=label;game.stats[s].B++;if(game.bases[0]){if(game.bases[1]){if(game.bases[2])runs(s,1);game.bases[2]=1}game.bases[1]=1}game.bases[0]=1;next()}
function hitLogic(n){const s=side(),bases=[0,0,0];game.stats[s].H++;game.bases.forEach((on,i)=>{if(on){if(i+n>=3)runs(s,1);else bases[i+n]=1}});if(n===4){runs(s,1);game.event='HOME RUN'}else{bases[n-1]=1;game.event=['','안타','2루타','3루타'][n]}game.bases=bases;next()}
function countLogic(k){if(k==='b'){game.b++;if(game.b===4)walkLogic('볼넷')}else{game.s++;if(game.s===3){game.event='삼진';outLogic()}}}
const total=s=>game.scores[s].reduce((a,b)=>a+(b||0),0);
function renderRecord(){if(!game){$('matchLeague').textContent='경기 준비가 필요합니다';$('matchStatus').textContent='대기';$('scoreTable').innerHTML='<div class="empty">경기 준비에서 저장된 팀과 선수를 불러오세요.</div>';$('batterName').textContent='라인업을 먼저 확정하세요';$('batterMeta').textContent='상단 경기 준비 → 명단 불러오기';return}const s=side(),p=current(),cols=Math.max(12,game.inn);$('matchLeague').textContent=game.league;$('matchStatus').textContent=game.finished?'경기 종료':'기록 중';$('scoreTable').innerHTML=`<table><thead><tr><th>TEAM</th>${Array.from({length:cols},(_,i)=>`<th>${i+1}</th>`).join('')}<th>R</th><th>H</th><th>E</th><th>B</th></tr></thead><tbody>${['a','h'].map(k=>`<tr><td>${esc(game.teamNames[k])} ${k===s?'◂':''}</td>${Array.from({length:cols},(_,i)=>`<td class="${i===game.inn-1&&s===k?'current':''}"><button data-action="cell" data-side="${k}" data-index="${i}" title="${i+1}회 점수 수정">${game.scores[k][i]??'·'}</button></td>`).join('')}<td class="total">${total(k)}</td>${['H','E','B'].map(v=>`<td><button data-action="stat" data-side="${k}" data-key="${v}">${game.stats[k][v]}</button></td>`).join('')}</tr>`).join('')}</tbody></table>`;
$('batterPhoto').innerHTML=photo(p,'portrait');$('batterName').textContent=p?`#${p[0]} ${p[1]}`:'선수 없음';$('batterMeta').textContent=`${p?.[2]||''} · ${game.teamNames[s]} · ${game.turns[s]+1}번 타자`;$('eventLabel').textContent=game.event;$('inningLabel').textContent=game.inn+'회 '+game.half;$('speed').value=game.speed||'';$('blankButton').textContent=game.blank?'화면 켜기':'화면 끄기';
for(const k of ['a','h']){const prefix=k==='a'?'away':'home';$(prefix+'Name').textContent=game.teamNames[k];$(prefix+'Lineup').innerHTML=line(k).map((q,i)=>`<button class="lineup-row ${k===s&&i===game.turns[k]?'current':''}" data-action="batter" data-side="${k}" data-index="${i}"><span>${i+1}</span><b>#${esc(q[0])}</b><strong>${esc(q[1])}</strong><small>${esc(q[2])}</small></button>`).join('');$(prefix+'Pitcher').innerHTML=`<small>현재 투수</small><select data-pitcher="${k}">${game.rosters[k].map((q,i)=>`<option value="${i}" ${game.pitchers[k]===i?'selected':''}>#${esc(q[0])} ${esc(q[1])}</option>`).join('')}</select>`}
$('countRows').innerHTML=[['B','b',3],['S','s',2],['O','o',2]].map(([label,k,max])=>`<div class="crow"><b>${label}</b><div class="dots">${Array.from({length:max},(_,i)=>`<i class="dot ${i<game[k]?label:''}"></i>`).join('')}</div><strong>${game[k]}</strong><button data-action="decrement" data-key="${k}" aria-label="${label} 감소">−</button><button data-action="count" data-key="${k}" aria-label="${label} 증가">＋</button></div>`).join('');game.bases.forEach((v,i)=>$('base'+(i+1)).classList.toggle('on',!!v));$('recentLog').innerHTML=game.log.slice(0,6).map(l=>`<div class="log-row"><small>${esc(l.time)}</small><span>${esc(l.label)}</span></div>`).join('')||'<small class="help">아직 입력한 기록이 없습니다.</small>';}
function renderTeams(){if(!team(editId))editId=teams[0]?.id;$('teamList').innerHTML=teams.map(t=>`<button data-action="editTeam" data-id="${esc(t.id)}" class="team-choice ${editId===t.id?'active':''}">${esc(t.name)}<small>${esc(t.league)} · ${t.players.length}명${t.sample?' · 임시 명단':''}</small></button>`).join('');const t=team(editId);if(!t){$('teamEditor').innerHTML='<div class="empty">팀을 등록하세요.</div>';return}$('teamEditor').innerHTML=`${t.sample?'<div class="notice">임의로 만든 테스트 선수 30명입니다. 실제 팀 명단이 아닙니다.'+(t.nameIncomplete?' 팀명은 첨부 이미지에서 잘린 표기이므로 정확한 이름으로 수정하세요.':'')+'</div>':''}<div class="team-fields"><label>팀명<input data-team-field="name" value="${esc(t.name)}"></label><label>소속 리그<select data-team-field="league">${leagues.map(l=>`<option ${l===t.league?'selected':''}>${esc(l)}</option>`).join('')}</select></label></div><div class="card-head"><h2>선수 명단</h2><button class="text-btn" data-action="playerAdd">＋ 선수 등록</button></div><p class="help">선수명 / 등번호 / 포지션 · 사진은 작게 압축하여 저장됩니다.</p>${t.players.map((p,i)=>`<div class="edit-player">${photo(p)}<input aria-label="선수명" data-player="${i}" data-field="1" value="${esc(p[1])}"><input aria-label="등번호" data-player="${i}" data-field="0" value="${esc(p[0])}"><input aria-label="포지션" data-player="${i}" data-field="2" value="${esc(p[2])}"><label class="button">사진 변경<input type="file" accept="image/png,image/jpeg,image/webp" data-photo="${i}" hidden></label><button data-action="playerDelete" data-index="${i}">삭제</button></div>`).join('')}`}
function renderHistory(){$('historyList').innerHTML=archive.map(g=>`<article class="card history-card"><div><small>${new Date(g.id).toLocaleDateString('ko-KR')} · ${esc(g.league)} · ${g.interrupted?'중단 보관':'종료'}</small><h3>${esc(g.teamNames.a)} vs ${esc(g.teamNames.h)}</h3><button data-action="exportGame" data-id="${g.id}">경기 데이터 내려받기</button></div><strong>${g.scores.a.reduce((a,b)=>a+(b||0),0)} : ${g.scores.h.reduce((a,b)=>a+(b||0),0)}</strong></article>`).join('')||'<div class="card empty">종료 · 저장한 경기가 여기에 표시됩니다.</div>'}
function download(name,data){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function askNumber(label,old){const value=prompt(label,String(old??0));if(value===null||value.trim()==='')return null;const n=Number(value);if(!Number.isInteger(n)||n<0||n>999){toast('0~999 사이의 정수를 입력하세요.');return null}return n}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){openPage(page.dataset.page);return}const btn=e.target.closest('[data-action]');if(!btn)return;const {action:a,side:s,index:ix,value:v,key:k,id}=btn.dataset,i=+ix,n=+v;
if(a==='load')return loadDraft();if(a==='start')return startGame();if(a==='entry'){const list=draft.entries[s],pos=list.indexOf(i);if(pos>=0)list.splice(pos,1);else if(list.length<9)list.push(i);else toast('출전 타순은 최대 9명입니다.');renderDraft();return}if(a==='move'){const l=draft.entries[s];if(i+n>=0&&i+n<l.length)[l[i],l[i+n]]=[l[i+n],l[i]];renderDraft();return}
if(a==='leagueAdd'){const name=prompt('새 리그 이름');if(name?.trim()&&!leagues.includes(name.trim())){leagues.push(name.trim());saveDB();selectors();$('leagueSelect').value=name.trim();filterTeams()}return}if(a==='teamAdd'){const name=prompt('팀 이름');if(name?.trim()){teams.push({id:'t'+Date.now(),name:name.trim(),league:leagues[0]||'기본 리그',players:[]});editId=teams.at(-1).id;saveDB();renderTeams()}return}if(a==='editTeam'){editId=id;openPage('teams');return}if(a==='playerAdd'){team(editId).players.push(['','신규선수','SS','']);saveDB();renderTeams();return}if(a==='playerDelete'){if(confirm('이 선수를 팀 명단에서 삭제할까요? 진행 중인 경기 명단은 유지됩니다.')){team(editId).players.splice(i,1);saveDB();renderTeams()}return}if(a==='backup')return download('안산야구_DB_백업.json',{version:1,teams,leagues});if(a==='exportGame')return download('야구경기_'+id+'.json',archive.find(g=>g.id===+id));
if(a==='undo'){if(undoStack.length){game=undoStack.pop();saveGame()}else toast('취소할 조작이 없습니다.');return}if(a==='finish'){if(!game||game.finished)return;if(confirm('경기를 종료하고 기록을 저장할까요?')){game.finished=true;archive.unshift(clone(game));persist('ansan-archive-v5',archive);undoStack=[];saveGame();toast('경기 기록을 저장했습니다.')}return}
if(a==='cell'){const val=askNumber('이닝 점수 수정',game?.scores[s][i]);if(val!==null)act('이닝 점수 수정',()=>game.scores[s][i]=val);return}if(a==='stat'){const val=askNumber(k+' 합계 수정',game?.stats[s][k]);if(val!==null)act(k+' 합계 수정',()=>game.stats[s][k]=val);return}
act(({hit:'안타',homer:'홈런',walk:'볼넷',hbp:'사구',out:'타자 아웃',strikeout:'삼진',runnerOut:'주자 아웃',foul:'파울',error:'실책 출루',fc:'야수 선택',side:'공수 교대',next:'다음 타자',base:'주자 수정',clearBases:'주자 비우기',clearCount:'B/S 초기화',count:'카운트 증가',decrement:'카운트 감소',inning:'이닝 변경',batter:'타순 선택',blank:'송출 화면 전환',normal:'기본 화면'})[a]||a,()=>{switch(a){case'hit':hitLogic(n);break;case'homer':hitLogic(4);break;case'walk':walkLogic('볼넷');break;case'hbp':walkLogic('사구');break;case'out':game.event='OUT';outLogic();break;case'strikeout':game.event='삼진';outLogic();break;case'runnerOut':game.event='주자 아웃 · 주자 위치 확인';outLogic(false);break;case'count':if(k==='o'){game.event='OUT';outLogic()}else countLogic(k);break;case'decrement':game[k]=Math.max(0,game[k]-1);break;case'foul':game.s=Math.min(2,game.s+1);game.event='파울';break;case'error':game.stats[opponent()].E++;game.event='실책 · 주자 위치 확인';game.bases[0]=1;next();break;case'fc':game.event='야수 선택 · 주자 위치 확인';game.bases[0]=1;next();break;case'side':switchSide();break;case'next':next();break;case'base':game.bases[n]^=1;break;case'clearBases':game.bases=[0,0,0];break;case'clearCount':game.b=game.s=0;break;case'inning':game.inn=Math.max(1,game.inn+n);runs(side(),0);break;case'batter':game.turns[s]=i;break;case'blank':game.blank=!game.blank;break;case'normal':game.blank=false;game.event='경기 진행';break;}});
});
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='leagueSelect'){filterTeams();return}if(el.id==='speed'){const n=Number(el.value);if(n>=0&&n<=200)act('구속 변경',()=>game.speed=n);else{toast('구속은 0~200 사이로 입력하세요.');renderRecord()}return}if(el.dataset.pitcher){act('투수 변경',()=>game.pitchers[el.dataset.pitcher]=+el.value);return}if(el.dataset.teamField){if(!el.value.trim()){toast('팀 이름을 입력하세요.');renderTeams();return}team(editId)[el.dataset.teamField]=el.value.trim();saveDB();return}if(el.dataset.player!==undefined){const value=el.value.trim();if(el.dataset.field==='1'&&!value){toast('선수 이름을 입력하세요.');renderTeams();return}team(editId).players[+el.dataset.player][+el.dataset.field]=value;saveDB();return}if(el.dataset.photo!==undefined){const file=el.files[0];if(!file)return;const target=team(editId).players[+el.dataset.photo];try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,320/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();target[3]=canvas.toDataURL('image/jpeg',.8);saveDB();renderTeams();toast('사진을 저장했습니다.')}catch{toast('사진을 읽을 수 없습니다. JPG·PNG 사진을 선택하세요.')}return}if(el.id==='restore'){try{const data=JSON.parse(await el.files[0].text());if(!Array.isArray(data.teams)||!Array.isArray(data.leagues)||!data.leagues.every(l=>typeof l==='string')||!data.teams.every(t=>typeof t.id==='string'&&typeof t.name==='string'&&data.leagues.includes(t.league)&&Array.isArray(t.players)&&t.players.every(p=>Array.isArray(p)&&p.length>=3&&typeof p[1]==='string')))throw Error();if(new Set(data.teams.map(t=>t.id)).size!==data.teams.length)throw Error();if(confirm('백업 파일의 팀·선수 DB로 교체할까요?')){teams=data.teams;leagues=data.leagues;saveDB();draft=null;renderTeams();toast('DB를 복원했습니다.')}}catch{toast('올바른 DB 백업 JSON 파일이 아닙니다.')}el.value=''}});
for(const t of teams)for(const p of t.players)if(!p[4])p[4]=samplePhoto(p);
saveDB();
if(game){for(const list of [...Object.values(game.lineups),...Object.values(game.rosters)])for(const p of list)if(!p[4]){const match=teams.flatMap(t=>t.players).find(q=>JSON.stringify(q.slice(0,3))===JSON.stringify(p.slice(0,3)));p[4]=match?.[4]||samplePhoto(p)}saveGame()}
selectors();renderRecord();

function renderDashboard(){
 $('dashboardMetrics').innerHTML=[['등록 팀',teams.length+' 팀'],['등록 선수',teams.reduce((n,t)=>n+t.players.length,0)+' 명'],['등록 리그',leagues.length+' 개'],['보관 경기',archive.length+' 경기']].map(([label,value])=>`<article><small>${label}</small><strong>${value}</strong></article>`).join('');
 $('dashboardMatch').innerHTML=game?`<small>${esc(game.league)} · ${game.finished?'종료':game.inn+'회 '+game.half}</small><div class="dashboard-score"><span>${esc(game.teamNames.a)}</span><strong>${total('a')} : ${total('h')}</strong><span>${esc(game.teamNames.h)}</span></div>`:'<p>진행 중인 경기가 없습니다. 경기 준비에서 팀을 선택하세요.</p>';
 $('dashboardHistory').innerHTML=archive.slice(0,3).map(g=>`<p>${esc(g.teamNames.a)} <b>${g.scores.a.reduce((n,v)=>n+(v||0),0)} : ${g.scores.h.reduce((n,v)=>n+(v||0),0)}</b> ${esc(g.teamNames.h)}</p>`).join('')||'<p>보관된 경기가 없습니다.</p>';
 $('dashboardTeams').innerHTML=teams.map(t=>`<button data-action="editTeam" data-id="${esc(t.id)}"><b>${esc(t.name)}</b><small>${t.players.length}명${t.sample?' · 테스트 명단':''}</small></button>`).join('');
 const src=localStorage.getItem('ansan-association-logo');if(src&&/^data:image\/(png|jpeg|webp);base64,/.test(src)){for(const id of ['headerLogo','dashboardLogo']){$(id).src=src;$(id).hidden=false}$('logoHint').textContent='전광판에도 같은 로고가 표시됩니다.';document.querySelector('.association-mark strong').hidden=true}
}
$('associationLogoUpload').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)){toast('PNG, JPG, WEBP 파일을 선택하세요.');return}try{const bitmap=await createImageBitmap(f),canvas=document.createElement('canvas'),scale=Math.min(1,400/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();if(persist('ansan-association-logo',canvas.toDataURL('image/png'))){renderDashboard();toast('협회 로고를 적용했습니다.')}}catch{toast('이미지를 읽을 수 없습니다. 다른 파일을 선택하세요.')}});
openPage('dashboard');
