import type { DB } from "./types";

/** 초기 샘플 데이터 (최초 1회 localStorage 에 적재). 고정 id 사용. */
export const SEED: DB = {
  people: [
    {
      id: "p1",
      name: "김복지",
      category: "지역주민",
      org: "행신2동",
      position: "주민자치위원",
      region: "행신동",
      phone: "010-1234-5678",
      email: "",
      importance: 2,
      memo: "복지 분야 의견 활발",
      createdAt: "2026-06-20T09:00:00.000Z",
    },
    {
      id: "p2",
      name: "이언론",
      category: "언론",
      org: "고양일보",
      position: "기자",
      region: "고양시",
      phone: "010-2222-3333",
      email: "lee@news.example",
      importance: 3,
      memo: "지역 현안 취재 담당",
      createdAt: "2026-06-18T09:00:00.000Z",
    },
    {
      id: "p3",
      name: "박공무",
      category: "공무원",
      org: "도로교통과",
      position: "팀장",
      region: "경기도청",
      phone: "031-000-0000",
      email: "",
      importance: 2,
      memo: "교통 민원 협의 창구",
      createdAt: "2026-06-15T09:00:00.000Z",
    },
  ],
  contacts: [
    {
      id: "c1",
      personId: "p1",
      channel: "대면",
      summary: "경로당 증설 관련 면담",
      contactedAt: "2026-06-22T05:00:00.000Z",
    },
    {
      id: "c2",
      personId: "p3",
      channel: "전화",
      summary: "행신동 신호체계 개선 협의",
      contactedAt: "2026-06-24T01:30:00.000Z",
    },
  ],
  minwon: [
    {
      id: "m1",
      title: "행신동 사거리 신호 대기시간 과다",
      content: "출퇴근 시간 신호 대기가 길어 정체가 심합니다.",
      personName: "김복지",
      category: "교통",
      status: "처리중",
      priority: "높음",
      assignee: "비서 정",
      dueDate: "2026-06-30",
      createdAt: "2026-06-23T23:40:00.000Z",
    },
    {
      id: "m2",
      title: "어린이 통학로 불법주정차",
      content: "초등학교 앞 불법주정차로 안전이 우려됩니다.",
      personName: "익명",
      category: "안전",
      status: "접수",
      priority: "긴급",
      assignee: "",
      dueDate: "2026-06-27",
      createdAt: "2026-06-25T00:10:00.000Z",
    },
    {
      id: "m3",
      title: "경로당 냉방기 교체 요청",
      content: "노후 냉방기 교체가 필요합니다.",
      personName: "김복지",
      category: "복지",
      status: "완료",
      priority: "보통",
      assignee: "비서 정",
      dueDate: "2026-06-20",
      createdAt: "2026-06-10T02:00:00.000Z",
    },
  ],
  events: [
    {
      id: "e1",
      title: "청년 일자리 정책 간담회",
      type: "행사",
      location: "행신동 주민센터",
      startAt: "2026-07-03T05:00:00.000Z",
      description: "지역 청년 채용 확대 방안 논의",
      status: "예정",
      attendees: ["김복지", "이언론"],
      report: "",
      createdAt: "2026-06-21T09:00:00.000Z",
    },
    {
      id: "e2",
      title: "도정 현안 보고회",
      type: "의정활동",
      location: "경기도의회",
      startAt: "2026-06-26T01:00:00.000Z",
      description: "상임위 현안 점검",
      status: "예정",
      attendees: [],
      report: "",
      createdAt: "2026-06-20T09:00:00.000Z",
    },
  ],
  prContents: [
    {
      id: "pr1",
      type: "보도자료",
      title: "장윤정 도의원, 청년 일자리 간담회 개최",
      body: "장윤정 경기도의원은 오는 7월 3일 행신동 주민센터에서 청년 일자리 정책 간담회를 개최한다고 밝혔다…",
      status: "검토",
      createdAt: "2026-06-22T09:00:00.000Z",
    },
  ],
  policyItems: [
    {
      id: "pol1",
      type: "5분발언",
      title: "지역 교통안전 인프라 확충 촉구",
      content: "존경하는 의장님, 그리고 동료 의원 여러분…",
      source: "행신동 교통 민원 다수",
      status: "검토",
      createdAt: "2026-06-19T09:00:00.000Z",
    },
  ],
  newsItems: [
    {
      id: "n1",
      title: "고양시 교통체증 민원 급증… 대책 시급",
      source: "고양일보",
      url: "",
      sentiment: "부정",
      keywords: ["교통", "민원", "고양"],
      summary: "지역 교통체증 관련 민원이 늘어 대책 마련이 필요하다는 보도.",
      publishedAt: "2026-06-24T22:00:00.000Z",
      createdAt: "2026-06-25T00:00:00.000Z",
    },
    {
      id: "n2",
      title: "경기도 청년 일자리 사업 확대 추진",
      source: "경기신문",
      url: "",
      sentiment: "긍정",
      keywords: ["청년", "일자리", "경기도"],
      summary: "경기도가 청년 일자리 사업을 확대한다는 긍정적 보도.",
      publishedAt: "2026-06-24T08:00:00.000Z",
      createdAt: "2026-06-25T00:00:00.000Z",
    },
  ],
};
